version: "3.8"
services:
  tf-dev:
    build:
      context: ../../../../
      dockerfile: research/object_detection/dockerfiles/1.15/Dockerfile
    container_name: xdhm_tf_dev_ctnr
    volumes:
      # RESUME this doesn't appear to be correct on the lhs
      - .:/home/tensorflow/models
    image: xdhm_tf_dev_img

