#!/usr/bin/env bash

echo "Running pipeline" >&2

cd /home/tensorflow/models/research

# TODO use...gosudo? so that ctrl+C kills this
# TODO pass in # of steps via command line
$exec python3 object_detection/model_main.py \
    --pipeline_config_path=object_detection/dockerfiles/1.15/pipeline.config \
    --model_dir=/model_dir \
    --num_train_steps=20 \
    --sample_0_of_n_eval_examples=1 \
    --alsologtostderr


