


FROM tensorflow/tensorflow:1.15.2-gpu-py3

ARG DEBIAN_FRONTEND=noninteractive

# TODO lock in the version on all this stuff

# Install apt dependencies
RUN apt-get update && apt-get install -y \
    git \
    gpg-agent \
    python3-cairocffi \
    protobuf-compiler \
    python3-pil \
    python3-lxml \
    python3-tk \
    wget

# Install gcloud and gsutil commands
# https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install google-cloud-sdk -y

# Add new user to avoid running as root
RUN useradd -ms /bin/bash tensorflow
USER tensorflow
WORKDIR /home/tensorflow

WORKDIR /home/tensorflow/models/research/

RUN cp object_detection/packages/tf1/setup.py ./
ENV PATH="/home/tensorflow/.local/bin:${PATH}"

RUN python -m pip install --user -U pip
RUN python -m pip install --user .
# Install pip dependencies
#RUN pip3 install --user absl-py
#RUN pip3 install --user contextlib2
#RUN pip3 install --user Cython
#RUN pip3 install --user jupyter
#RUN pip3 install --user matplotlib
#RUN pip3 install --user pycocotools
#RUN pip3 install --user tf-slim

# These two steps are done outside and mounted now
# COPY --chown=tensorflow . /home/tensorflow/models
# RUN (cd /home/tensorflow/models/research/ && \
#    protoc object_detection/protos/*.proto --python_out=.)

ENV TF_CPP_MIN_LOG_LEVEL 3
