#!/usr/bin/env bash

set -e

echo "Running pipeline" >&2

cd /home/tensorflow/models/research

#pip install debugpy -t /tmp ;

# TODO use...gosu? so that ctrl+C kills this
# TODO pass in # of steps via command line
# TODO make debug depend on a passed-in flag or a special "debug" script that calls this
# If you don't have the 0.0.0.0 it'll only listen on localhost (local connections only) and you'll spend 3 hours confused
#$exec python3  /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
$exec python3 debugpy --wait-for-client --listen 0.0.0.0:5678 \
    object_detection/model_main.py \
        --pipeline_config_path=object_detection/dockerfiles/tf1/pipeline.config \
        --model_dir=/model_dir \
        --num_train_steps=20 \
        --sample_0_of_n_eval_examples=1 \
        --alsologtostderr


